### PR TITLE
EntraID Org mapping docs update

### PR DESCRIPTION
**Pull request by dlehman83**
* Update Entra ID section with org mapping details
* Fix all markdown / spacing / formatting errors I could find.
* Fix a few wording / spelling issues.

### CODE REVIEW

**Comment by Timshel** [comment]
Hey,
Thank you for the fixes :smile:.
Just rebased so the PR is kind of funky :sweat:.
Backported some of the fixes on `sso.md` to the `sso-support` branch since it's the one used for PR, hope you don't mind.

**Comment by dlehman83** [comment]
I can rebase my fork to your sso support branch and repush if needed.  
I thought the main branch was where to go.  

Can you tell me what branch your docker images are based on.  I've been testing with your docker image.  I had an idea I wanted to try, but can't get it to compile on my machine.  

Also what features are additional vs what is going into the PR? I want to focus my testing on what is needed.  

Thanks,

**Comment by Timshel** [comment]
You can rebase on top of `master`, I already backported what I believed to be relevant.
The docker is built using `master`, not sure why you have issues building, a `cargo build --features sqlite,mysql,postgresql` should do the job. Alternatively you can try to build the docker image with a simple `docker build .`
Features specific to the `main` branch are roles and organization mapping.

**Comment by dlehman83** [comment]
Its organizational mapping that I was working on so, not something to put in the sso support branch if that will be a separate PR.
I have an ubuntu VM that when I run the docker build or bake.sh script it only gets so far and just hangs / freezes the VM.  I've tried giving it more CPU but not sure what is going on.  

I copied to to windows WSL and was able to build the image, but am having trouble pushing the image up to that VM to test it.  

I've only ever followed directions to use a docker compose file. This is my first time with trying to build my own docker image and will be my first time with rust.

**Comment by dlehman83** [comment]
I leered about the docker save and load commands, so I was able to transfer the image that way.  I'm not sure what I'm missing.  
I have made no code changes yet, because I want to just know that basic functions work before my own changes break something.
I run the bake.sh script on windows WSL
I use docker save to a tar file
I copy it up to the Ubuntu VM and use docker load
docker image ls shows me my image

when running the image, I get /start.sh file does not exist.

**Comment by Timshel** [comment]
I believe the bake is to build all the different platform.
You should be able to just build the `.dockerfile` at the root of the project with something like `DOCKER_BUILDKIT=1 docker build . -t your_image_name`.

Then probably check that the image is valid and should contain :

 - /vaultwarden
 - /start.sh
 - /web-vault

**Comment by dlehman83** [comment]
I finally got it to compile, I needed to give it more RAM.  I don't know anything about rust though and my changes are not working.  I thought it would be a minor change.  

Anyway for this pull request I've rebased so feel free to merge / close.  

I'll either open another pull request if I get it working, or just put in a feature request.  

Thank you

**Pull request merged**
